version: 2.1

executors:
  python3:
    docker:
      - image: cimg/python:3.10.2
  ubuntu:
    docker:
      - image: cimg/base:stable

commands:
  pylint:
    description: Run pylint
    steps:
      - run:
          command: pylint

jobs: {}

workflows:
  version: 2

  on-commit:
    {}

  on-merge:
    {}

  on-tag:
    # Publish this package to PyPI.
    {}